# Generated by Django 5.0.6 on 2024-12-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Message')),
                ('image', models.ImageField(blank=True, null=True, upload_to='discord_images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
